apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: trip-viewer-ingress
  namespace: front-end
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tripviewer
          servicePort: 80
        path: /(.*)
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: trip-service
          servicePort: 80
        path: /api/trips/healthcheck
        pathType: Exact
      - backend:
          serviceName: poi-service
          servicePort: 80
        path: /api/poi
        pathType: Prefix
      - backend:
          serviceName: user-profile
          servicePort: 80
        path: /api/user
        pathType: Prefix
      - backend:
          serviceName: user-java-service
          servicePort: 80
        path: /api/user-java
        pathType: Prefix