apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryois2716.azurecr.io/trips:latest
        env:
          - name: SQL_DBNAME
            value: mydrivingDB
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/secrets"
            readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"
            # nodePublishSecretRef:
            #   name: secrets-store-creds
---
apiVersion: v1
kind: Service
metadata:
  name: trip-service
  namespace: api
spec:
  selector:
    app: trips
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80