apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-profile
  template:
    metadata:
      labels:
        app: user-profile
    spec:
      containers:
      - name: user-profile
        image: registryois2716.azurecr.io/userprofile:latest
        env:
          - name: SQL_DBNAME
            value: mydrivingDB
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/secrets"
            readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"
            nodePublishSecretRef:
              name: secrets-store-creds
---
apiVersion: v1
kind: Service
metadata:
  name: user-profile
  namespace: api
spec:
  selector:
    app: user-profile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80