apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: team6vault
    objects: |
      array:
        - |
          objectName: sql-user              
          objectType: secret
          objectAlias: SQL_USER
          objectVersion: ""
        - |
          objectName: sql-password 
          objectAlias: SQL_PASSWORD            
          objectType: secret
          objectVersion: ""
        - |
          objectName: sql-server   
          objectAlias: SQL_SERVER           
          objectType: secret
          objectVersion: ""
    tenantId: d298f44f-e70b-476a-96fa-6e5aca73692e