apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: v1
kind: Namespace
metadata:
  name: front-end
---
apiVersion: v1
kind: Namespace
metadata:
  name: csi
---
apiVersion: v1
kind: Namespace
metadata:
  name: insurance